environment:
  matrix:
    - nodejs_version: STABLE
cache:
  - node_modules -> package.json

build_script:
  - yarn config set yarn-offline-mirror ./node_modules/
  - yarn install --ignore-engines
  - yarn build 

after_build:
  - yarn gulp compress

artifacts:
  - path: build\*.tar.gz
    name: PopcornTime

