environment:
  matrix:
    - nodejs_version: STABLE
cache:
  - node_modules -> package.json

# Install scripts. (runs after repo cloning)
install:
  # install modules
  - yarn config set yarn-offline-mirror ./node_modules/
  - yarn install --ignore-engines
  - yarn build 
  - yarn gulp compress
  - dir build\

# Post-install test scripts.
test_script:
  - node --version
  - yarn --version

artifacts:
  - path: build\Popcorn-Time-0.3.10_win64.tar.gz
    name: Popcorn-Time-{version}

deploy:
- provider: Environment
  name: Staging
