environment:
  matrix:
    - nodejs_version: STABLE
cache:
  - node_modules -> package.json

# Install scripts. (runs after repo cloning)
install:
  # install modules
  - yarn config set yarn-offline-mirror ./node_modules/
  - yarn install --ignore-engines
  - yarn build 
  - yarn gulp compress
  - move build\Popcorn-Time-0.3.10_win64.tar.gz .

# Post-install test scripts.
test_script:
  - node --version
  - yarn --version

artifacts:
  - path: Popcorn-Time-0.3.10_win64.tar.gz

deploy:
  description: 'Windows Release'
  provider: GitHub
  auth_token:
    secure: wKYGmYxyZoGANT1qraz3HzsUN9tiYx9pvF3KpILJZ/UQtC+EC5XHsnxKNtCjDUhb # your encrypted token from GitHub
  artifact: /.*\.tar.gz/
  on:
    appveyor_repo_tag: false      