language: node_js

node_js:
  - stable

cache:
  yarn: true
  directories:
    - node_modules
    
before_install:
  - yarn config set yarn-offline-mirror ./node_modules/
  - yarn install --ignore-engines
  - yarn build 

after_build:
  - yarn gulp compress

artifacts:
  - path: build\*.tar.gz
    name: PopcornTime

deploy:
  description: 'Linux Release'
  provider: GitHub
  auth_token:
    secure: wKYGmYxyZoGANT1qraz3HzsUN9tiYx9pvF3KpILJZ/UQtC+EC5XHsnxKNtCjDUhb # your encrypted token from GitHub
  artifact: /.*\.tar.gz/
  on:
    appveyor_repo_tag: false

notifications:
  email: false